Update patch set 2
Patch Set 2:

I think this one might be causing issues when visual studio builds are configured in a cygwin/msys environment:
vp8/common/threading.h(76): fatal error C1083: Cannot open include file: 'semaphore.h': No such file or directory

at least it auto-bisected here. I haven't had a closer look.

Patch-set: 2