Update patch set 9
Patch Set 9:

oops, I forgot this might be an issue:

active_map_refresh_test.cc:75:58: error: 'dynamic_cast' not permitted with -fno-rtti
         dynamic_cast<libvpx_test::Y4mVideoSource *>(video);

we use this in a nightly too due to a ubsan bug

Patch-set: 9