Update patch set 1
Patch Set 1:

msvc 2008 has more of an issue with this:

Error	2	error C2536: 'std::tr1::tuple<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9>::std::tr1::tuple<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9>::f0_' : cannot specify explicit initializer for arrays	c:\opt\MinGW\msys\1.0\home\jzern\external\libvpx\third_party\googletest\src\include\gtest\gtest.h	885	test_libvpx

so it will probably need to be rewritten a bit

Patch-set: 1
Reviewer: James Zern <1002219@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0
Label: Commit-Queue=0
Label: Verified=0