Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2: Code-Review-2
> > 
> > this still isn't quite right. it will crash in 32-bit builds (--target=x86-linux-gcc)
> 
> I can't reproduce the crash in 32-bit builds. The configure command line I'm using:
> 
> https://sites.google.com/a/google.com/webm/howto/jenkins-like-builds/build-with-asan
> 

this link isn't that important, but try not to post internal only urls to public forums.

> The command line in the bug can't run on my machine. config.log errors:
> clang++ -fsanitize= -m64 -g -o /tmp/vpx-conf-169452-8169.x /tmp/vpx-conf-169452-8169.o -lpthread
> /tmp/vpx-conf-169452-8169.o: In function `asan.module_ctor':
> /tmp/vpx-conf-169452-8169.c:(.text+0x12): undefined reference to `__asan_init'
> /tmp/vpx-conf-169452-8169.c:(.text+0x18): undefined reference to `__asan_version_mismatch_check_v8'
> clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Does the difference of configure arguments expose the crash in 32-bit build?

you should post your configure line, it looks like -fsanitize isn't set correctly and you're doing a 64-bit build there (-m64).

this should be enough:

CC=clang
CXX=clang++
LD=clang++
CFLAGS=' -fsanitize=address -fno-strict-aliasing -fno-omit-frame-pointer -fno-optimize-sibling-calls'
CXXFLAGS=' -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls -g'
LDFLAGS=-fsanitize=address
./configure --target=x86-linux-gcc --disable-install-docs --enable-unit-tests --enable-debug --enable-ccache --enable-postproc --enable-vp9-postproc

...

[ RUN      ] VP9/DatarateOnePassCbrSvc.OnePassCbrSvc2SpatialLayersDenoiserOn/0
ASAN:DEADLYSIGNAL
=================================================================
==111272==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x08ccd456 bp 0xffacbe48 sp 0xffacbe10 T0)
==111272==The signal is caused by a READ memory access.
==111272==Hint: address points to the zero page.
    #0 0x8ccd455  vpx_dsp/x86/deblock_sse2.asm:110

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV vpx_dsp/x86/deblock_sse2.asm:110
==111272==ABORTING

or just do:
configure --target=x86-linux-gcc --enable-debug --enable-vp9-postproc

Patch-set: 2
Reviewer: James Zern <1002219@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>