Update patch set 1
Patch Set 1:

All tests pass with this change (msvs + mingw-w64):

[----------] Global test environment tear-down

[==========] 285 tests from 32 test cases ran. (128577 ms total)

[  PASSED  ] 285 tests.

Prior to recent changes:

...

test/xmm_register_check.h(66): error: Value of: *xmm_post

  Actual: 16-byte object <96-96 97-98 99-9B 9D-9D 9D-9B 9A-9B 9A-99 97-98>

Expected: *xmm_pre

Which is: 16-byte object <9E-9F A2-A2 A1-A1 A0-9F 9E-9C 9C-9D 9D-9D 9D-9D>

xmm11 has been modified!

test/xmm_register_check.h(45): error: Value of: Check()

  Actual: false

Expected: true

[  FAILED  ] TestVectorSequence/TestVectorTest.MD5Match/35, where GetParam() = "vp80-03-segmentation-1410.ivf" (44 ms)

...


[----------] Global test environment tear-down

[==========] 285 tests from 32 test cases ran. (57905 ms total)

[  PASSED  ] 166 tests.

[  FAILED  ] 119 tests, listed below:

Patch-set: 1
Label: Code-Review=0
Label: Verified=0