Update patch set 2
Patch Set 2:

The change failed because of this:
http://build.webmproject.org/jenkins/job/libvpx%20compile%20options/8459/arch=x86-linux-gcc,config=shared,label=slave/console

  [LD] vp9_spatial_scalable_encoder
vp9_spatial_scalable_encoder.c.o: In function `main':
vp9_spatial_scalable_encoder.c:(.text.startup+0x840): undefined reference to `vpx_svc_get_layer_resolution'
collect2: ld returned 1 exit status
make[1]: *** [vp9_spatial_scalable_encoder] Error 1
make: *** [.DEFAULT] Error 2

You can reproduce/check with:
../libvpx/configure --target=x86-linux-gcc --enable-install-docs --enable-install-srcs --enable-pic --enable-shared --enable-werror --enable-ccache

Patch-set: 2
Label: Code-Review=0
Label: Commit-Queue=0
Label: Verified=0