Revert "VP8 for ARMv8 by using NEON intrinsics 08"
This reverts commit a5d79f43b963ced59b462206faf3b7857bdeff7b

There is an issue with gcc 4.6 in the Android NDK:
loopfilter_neon.c: In function 'vp8_loop_filter_vertical_edge_y_neon':
loopfilter_neon.c:394:1: error: insn does not satisfy its constraints:

Change-Id: I2b8c6ee3fa595c152ac3a5c08dd79bd9770c7b52