fix aarch64 realtime-only build
After the additions of vp9_temporal_filter_neon_dotprod.c and
vp9_temporal_filter_neon_i8mm.c. These are only used needed in
non-realtime-only builds. Fixes:

vp9/encoder/arm/neon/vp9_temporal_filter_neon_dotprod.c:82:5: error:
  call to undeclared function 'vpx_convolve12_horiz_c'; ISO C99 and
  later do not support implicit function declarations
  [-Wimplicit-function-declaration]
    vpx_convolve12_horiz_c(src, src_stride, dst, dst_stride, filter, x0_q4,
    ^
vp9/encoder/arm/neon/vp9_temporal_filter_neon_dotprod.c:75:6: warning:
  no previous prototype for function 'vpx_convolve12_horiz_neon_dotprod'
  [-Wmissing-prototypes]
void vpx_convolve12_horiz_neon_dotprod(const uint8_t *src, ptrdiff_t src_stride,

...

vp9/encoder/arm/neon/vp9_temporal_filter_neon_i8mm.c:71:5: error: call
  to undeclared function 'vpx_convolve12_horiz_c'; ISO C99 and later do
  not support implicit function declarations
  [-Wimplicit-function-declaration]
    vpx_convolve12_horiz_c(src, src_stride, dst, dst_stride, filter, x0_q4,
    ^
vp9/encoder/arm/neon/vp9_temporal_filter_neon_i8mm.c:64:6: warning: no
  previous prototype for function 'vpx_convolve12_horiz_neon_i8mm'
  [-Wmissing-prototypes]

Change-Id: Ie9a701ade64eaec2a7759f59f38799ee9ea98b5d