Revert "third_party/googletest: update to v1.8.1"
This reverts commit 7d777ce6136d7325a102524b6d80c19bd420e4b6.

Reason for revert: Generates build warnings on VS10/VS12

third_party\googletest\src\include\gtest/gtest-printers.h(1036): error C2770: invalid explicit template argument(s) for 'AddReference<const ::std::tr1::tuple_element<I,std::tr1::tuple<_Arg0,_Arg1>>::type>::type testing::internal::TuplePolicy<TupleT>::get(const std::tr1::tuple<_Arg0,_Arg1> &)' [C:\src\buildbot\test-libvpx\tests\i9vRsze8hQ\.build-x86-win32-vs10\test_libvpx.vcxproj]

Original change's description:
> third_party/googletest: update to v1.8.1
>
> BUG=webm:1559
>
> Change-Id: I7a0b16c7bf3f97db2d8650a190b93aae7e12a948

TBR=tomfinegan@chromium.org

Bug: webm:1559
Change-Id: Ia1a7354084c778a4c4e91b33fef6462e88986d1e