vpx_fdct16x16_avx2: add missing cast
Fixes:
vpx_dsp/x86/fwd_txfm_avx2.c:378:50: error: incompatible pointer types
  passing 'int16_t *' (aka 'short *') to parameter of type
  'tran_low_t *' (aka 'int *') [-Werror,-Wincompatible-pointer-types]

Change-Id: I9f50547c1fc885c24b4b91e4c7d6857d397cceed