Update patch set 1
Patch Set 1:

This just annoyed me again. Errors:

    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:84:18: warning: implicit declaration of function     '_mm256_broadcastsi128_si256' is invalid in C99 [-Wimplicit-function-declaration]
      filtersReg32 = MM256_BROADCASTSI128_SI256(filtersReg);
                     ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:48:41: note: expanded from macro 'MM256_BROADCASTSI128_SI256'
    #  define MM256_BROADCASTSI128_SI256(x) _mm256_broadcastsi128_si256(x)
                                            ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:84:16: error: assigning to '__m256i' from incompatible type 'int'
      filtersReg32 = MM256_BROADCASTSI128_SI256(filtersReg);
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:329:16: error: assigning to '__m256i' from incompatible type 'int'
      filtersReg32 = MM256_BROADCASTSI128_SI256(filtersReg);
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I'm on xcode v5.0, which I assume is the cause of this weirdness. More info in case your curious about other preproc vals:

        [CC] vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c.o
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:42:11: warning: gcc = gcc [-W#pragma-messages]
      #pragma message "gcc = " STRING(gcc)
              ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:43:11: warning: __GNUC__ = 4 [-W#pragma-messages]
      #pragma message "__GNUC__ = " STRING(__GNUC__)
              ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:44:11: warning: __GNUC_MINOR__ = 2 [-W#pragma-messages]
      #pragma message "__GNUC_MINOR__ = " STRING(__GNUC_MINOR__)
              ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:45:11: warning: __clang_major__ = 5 [-W#pragma-messages]
      #pragma message "__clang_major__ = " STRING(__clang_major__)
              ^
    ../vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c:46:11: warning: __clang_minor__ = 0 [-W#pragma-messages]
      #pragma message "__clang_minor__ = " STRING(__clang_minor__)

Patch-set: 1
Label: Code-Review=0
Label: Commit-Queue=0
Label: Verified=0