gen_msvs_vcxproj: set C++ language standard to C++17
This is required since:
  f14de9d29 Update to GoogleTest 1.17.0

Visual Studio defaults to `/std:c++14`.

Fixes:
 googletest\src\include\gtest\internal\gtest-port.h(273,1):
 error C1189: #error:  C++ versions less than C++17 are not supported.

Change-Id: I1becf88a9063c9889c3097928658a1cfe41e58dd